FROM mariadb

#COPY ./docker/mysql-initialdata.sql /docker-entrypoint-initdb.d/init.sql
#COPY ./docker/db-init.sh /docker-entrypoint-initdb.d/init.sh
COPY ./docker/db-tcpcon.cnf /etc/mysql/conf.d/50-tcpcon.cnf
#COPY ./docker/docker-entrypoint.sh /
#RUN chmod a+x /docker-entrypoint.sh
#RUN chmod a+x /docker-entrypoint-initdb.d/init.sh
WORKDIR /
